### ISSUE TITLE
Missing song CSS from local.css

### ISSUE THREAD

**Issue by robinwhittleton** [johnrambow/margaret-wilson_the-able-mclaughlins#4]
https://github.com/johnrambow/margaret-wilson_the-able-mclaughlins/blob/9e1211399feacf5994741f243188a0e198f8ce5d/src/epub/css/local.css#L4-L7

Can you review SEMOS 7.5.2 / 7.5.3 https://standardebooks.org/manual/1.6.2/single-page#7.5.2 and add in the missing song CSS?

**Comment by johnrambow** [comment]
OK, i copied in the following styling (I left off the P + P one, since it's not used in this single-stanza song and therefore leads to a lint error.)

@charset "utf-8";
@namespace epub "http://www.idpf.org/2007/ops";

[epub|type~="z3998:song"] p{
	text-align: initial;
	text-indent: 0;
}
[epub|type~="z3998:song"] p > span{
	display: block;
	padding-left: 1em;
	text-indent: -1em;
}

[epub|type~="z3998:song"] p > span + br{
	display: none;
}
